version: "3"
services:
  jupyter:
    build:
      context: ./docker/
    image: ${JUPYTER_IMAGE_NAME}:${VERSION}
    container_name: bentoml-serving
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      BENTOML_HOME: /${BENTOML_HOME}
    volumes:
      - ./:/opt/project
      - ./${BENTOML_HOME}:/${BENTOML_HOME}
    stdin_open: true
    tty: true
    command: >
      bash -c "
      cd / && jupyter notebook --no-browser --allow-root --ip='*' --port=8888 --NotebookApp.password='' --NotebookApp.token=''
      "
