version: "3"
services:
  jupyter:
    build:
      context: ./docker/
    image: ${JUPYTER_IMAGE_NAME}:${VERSION}
    container_name: bentoml-serving
    ports:
      - "${JUPYTER_PORT}:8888"
    #environment:
    #  CHOWN_HOME: "yes"
    #  CHOWN_HOME_OPTS: '-R'
    #  CHOWN_EXTRA: ${JUPYTER_CHOWN_EXTRA}
    #  CHOWN_EXTRA_OPTS: '-R'
    #  JUPYTER_TOKEN: ""
    volumes:
      - ./:/opt/project
    stdin_open: true
    tty: true
    command: >
      bash -c "
      cd / && jupyter notebook --no-browser --allow-root --ip='*' --port=8888 --NotebookApp.password='' --NotebookApp.token=''
      "
