version: "3"
services:
  mlflow:
    build: ./docker/mlflow
    image: mlflow-image
    container_name: mlflow
    ports:
      - "11000:8888"
      - "5000:5000"
    #platform: linux/arm64
    volumes:
      - ./:/opt/project
      #- type: bind
      #  source: $HOME/.aws/config
      #  target: /root/.aws/config
      #  read_only: true
      #- type: bind
      #  source: $HOME/.aws/credentials
      #  target: /root/.aws/credentials
        #read_only: true
    stdin_open: true
    tty: true
    environment:
      JUPYTER_TOKEN: ""
    command: >
      bash -c "
      cd / && jupyter notebook --no-browser --allow-root --ip='*' --port=8888 --NotebookApp.password='' --NotebookApp.token=''
      "
